: ITER  DUP 1 AND 0= IF  2/  ELSE  DUP 2* + 1+  THEN ;
: COLLATZ  0 SWAP  BEGIN  DUP 1 >  WHILE  SWAP 1+ SWAP  ITER  REPEAT  DROP ;
: MAXLEN  0 SWAP  BEGIN   DUP COLLATZ ROT MAX SWAP  1- DUP 0= UNTIL DROP ;

1000000 MAXLEN .
BYE
